apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-app
  namespace: app
  labels:
    app: sample-app
spec:
  replicas: 10 # pods수 조정
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest # 사용자의 요청으로 nginx로 변경 (기존: yxxunseo/sample-app:test)
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
  strategy:
    canary:
      steps:
        - setWeight: 10 # step 1 (트래픽 10%)
        - pause: {duration: 1m} # 1분 딜레이
        - setWeight: 50
        - pause: {duration: 1m}
        - setWeight: 100
      canaryService: sample-app-canary # 카나리 새 버전
      stableService: sample-app-stable # 기존 서비스
